### ISSUE TITLE
vite.config配置相对路径无效

### ISSUE THREAD

**Issue by xinnicai** [JeremyWu917/jeremy-ui#3]
![image](https://user-images.githubusercontent.com/30997380/177234007-f21f53e9-2008-43a5-8611-c882f2c6e4fc.png)
![image](https://user-images.githubusercontent.com/30997380/177234039-444a74e9-c117-4825-b13f-f9afdf7b1af9.png)

在rollup.config中也无效
![image](https://user-images.githubusercontent.com/30997380/177235094-c5d73e3e-ba22-4ca7-a5d1-30d740e61318.png)
![image](https://user-images.githubusercontent.com/30997380/177235139-4a54f24e-6345-4135-b3f4-a1d6e64b7ece.png)

**Comment by JeremyWu917** [comment]
依赖项版本不兼容，请检查依赖项版本
