### ISSUE TITLE
引入外部ui库无效

### ISSUE THREAD

**Issue by xinnicai** [JeremyWu917/jeremy-ui#4]
![image](https://user-images.githubusercontent.com/30997380/177241621-6fca6b9d-a29d-4d18-a757-2713b8b858af.png)
![image](https://user-images.githubusercontent.com/30997380/177241664-cf048874-91fa-4966-b8ea-a15e97ea636c.png)
require.cjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/node". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by JeremyWu917** [comment]
依赖性版本兼容问题
